# Generated by Django 4.2.2 on 2023-07-07 16:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_collection'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Collection',
        ),
    ]
