INSERT INTO main_app_movie(name, image, release_date, synopsis, rating)
    VALUES
        ('No Country for Old Men', 'https://m.media-amazon.com/images/I/71OyIH442IL._AC_UY436_FMwebp_QL65_.jpg', 'May 19th, 2007', 'No Country for Old Men is a 2007 American neo-Western crime thriller film written and directed by Joel and Ethan Coen, based on Cormac McCarthys 2005 novel of the same name. Starring Tommy Lee Jones, Javier Bardem, and Josh Brolin, the film is set in the desert landscape of 1980 West Texas.[2] The film revisits the themes of fate, conscience and circumstance that the Coen brothers had explored in the films Blood Simple (1984), Raising Arizona (1987), and Fargo (1996). The film follows three main characters: Llewelyn Moss (Brolin), a Vietnam War veteran and welder who stumbles upon a large sum of money in the desert; Anton Chigurh (Bardem), a hitman who is sent to recover the money and Ed Tom Bell (Jones), a sheriff investigating the crime. The film also stars Kelly Macdonald as Mosss wife Carla Jean, and Woody Harrelson as a bounty hunter seeking Moss and the return of the $2 million.', '5');
    VALUES
        ('There Will Be Blood', 'https://m.media-amazon.com/images/I/81uCq81ICML._AC_UY436_FMwebp_QL65_.jpg', 'December 26th, 2007', 'There Will Be Blood is a 2007 American epic period drama film written and directed by Paul Thomas Anderson, loosely based on the 1927 novel Oil! by Upton Sinclair. It stars Daniel Day-Lewis as Daniel Plainview, a silver miner turned oilman on a ruthless quest for wealth during Southern Californias oil boom of the late 19th and early 20th centuries. Paul Dano, Kevin J. OConnor, Ciarán Hinds, and Dillon Freasier co-star.', '5');
    VALUES
        ('Primer', 'https://m.media-amazon.com/images/I/518oSjMM6tL._AC_UY436_FMwebp_QL65_.jpg', 'October 8th, 2004', 'Primer is a 2004 American independent psychological science fiction film about the accidental discovery of time travel. The film was written, directed, produced, edited and scored by Shane Carruth, who also stars with David Sullivan. Primer is of note for its extremely low budget, experimental plot structure, philosophical implications, and complex technical dialogue, which Carruth, a college graduate with a degree in mathematics and a former engineer, chose not to simplify for the sake of the audience. The film collected the Grand Jury Prize at the 2004 Sundance Film Festival, before securing a limited release in the United States, and has since gained a cult following.', '4');
    VALUES
        ('Interstellar', 'https://m.media-amazon.com/images/I/A1JVqNMI7UL._AC_UY436_FMwebp_QL65_.jpg', 'October 26th, 2014', 'Interstellar is a 2014 epic science fiction film co-written, directed, and produced by Christopher Nolan. It stars Matthew McConaughey, Anne Hathaway, Jessica Chastain, Bill Irwin, Ellen Burstyn, Matt Damon, and Michael Caine. Set in a dystopian future where humanity is embroiled in a catastrophic blight and famine, the film follows a group of astronauts who travel through a wormhole near Saturn in search of a new home for humankind. Brothers Christopher and Jonathan Nolan wrote the screenplay, which had its origins in a script Jonathan developed in 2007. Kip Thorne, a Caltech theoretical physicist and 2017 Nobel laureate in Physics,[4] was an executive producer, acted as a scientific consultant, and wrote a tie-in book, The Science of Interstellar. Cinematographer Hoyte van Hoytema shot it on 35 mm movie film in the Panavision anamorphic format and IMAX 70 mm. Principal photography began in late 2013 and took place in Alberta, Iceland, and Los Angeles. Interstellar uses extensive practical and miniature effects and the company Double Negative created additional digital effects.', '4');
    VALUES
        ('2001: A Space Odyssey', 'https://m.media-amazon.com/images/I/81UCF3OAufL._AC_UY436_FMwebp_QL65_.jpg', 'April 3rd, 1968', '2001: A Space Odyssey is a 1968 epic science fiction film produced and directed by Stanley Kubrick. The screenplay was written by Kubrick and science fiction author Arthur C. Clarke, and was inspired by Clarkes 1951 short story The Sentinel and other short stories by Clarke. Clarke also published a novelisation of the film, in part written concurrently with the screenplay, after the films release. The film stars Keir Dullea, Gary Lockwood, William Sylvester, and Douglas Rain, and follows a voyage by astronauts, scientists and the sentient supercomputer HAL to Jupiter to investigate an alien monolith.', '5');
    VALUES
        ('Triangle of Sadness', 'https://m.media-amazon.com/images/I/71H+kh2OrZL._AC_UY436_FMwebp_QL65_.jpg', 'October 28th, 2022', 'Triangle of Sadness is a 2022 satirical black comedy written and directed by Ruben Östlund in his English-language feature film debut. The film stars Harris Dickinson, Charlbi Dean (in her last role), Dolly de Leon, Zlatko Burić, Henrik Dorsin, Vicki Berlin, and Woody Harrelson. The film follows a celebrity couple on a luxury cruise with wealthy guests. Triangle of Sadness had its world premiere at the 2022 Cannes Film Festival on 21 May 2022, where it received an eight-minute standing ovation and won the Palme dOr. The film received generally positive reviews, while de Leons performance received international praise, garnering her first Golden Globe and BAFTA nominations for her supporting role. It also won four European Film Awards, including the Best Film award, and received three nominations at the 95th Academy Awards: Best Picture, Best Director and Best Original Screenplay.', '4');
    VALUES
        ('Parasite', 'https://m.media-amazon.com/images/I/71Sw1SmxoEL._AC_UY436_FMwebp_QL65_.jpg', 'May 21st, 2019', 'Parasite (Korean: 기생충; Hanja: 寄生蟲; RR: Gisaengchung) is a 2019 South Korean black comedy thriller film directed by Bong Joon-ho, who co-wrote the screenplay with Han Jin-won and co-produced. The film, starring Song Kang-ho, Lee Sun-kyun, Cho Yeo-jeong, Choi Woo-shik, Park So-dam, Jang Hye-jin, Park Myung-hoon and Lee Jung-eun, follows a poor family who scheme to become employed by a wealthy family, infiltrating their household by posing as unrelated, highly qualified individuals.', '4');
    VALUES
        ('The Northman', 'https://m.media-amazon.com/images/I/71OGopDkYtL._AC_UY436_FMwebp_QL65_.jpg', 'April 22nd, 2022', 'The Northman is a 2022 American epic historical action thriller film directed by Robert Eggers, who co-wrote the screenplay with Sjón. Based on the legend of Amleth, the film stars Alexander Skarsgård (who also produced), Nicole Kidman, Claes Bang, Anya Taylor-Joy, Ethan Hawke, Björk and Willem Dafoe. The plot centers on Amleth, a Viking prince who sets out on a quest to avenge the murder of his father. The film is heavily influenced by Norse mythology.', '4');
    VALUES
        ('The Banshees of Inisherin', 'https://m.media-amazon.com/images/I/81-DmthvMwL._AC_UY436_FMwebp_QL65_.jpg', 'October 21st, 2022', 'The Banshees of Inisherin is a 2022 black tragicomedy film directed, written, and co-produced by Martin McDonagh.[6][7][8] Set on a remote, fictional island off the west coast of Ireland,[a] the film stars Colin Farrell and Brendan Gleeson as two lifelong friends who find themselves at an impasse when one abruptly ends their relationship, with alarming consequences for both of them; Kerry Condon and Barry Keoghan also star. It reunites Farrell and Gleeson, who previously worked together on McDonaghs directorial debut, In Bruges (2008).', '4');
    VALUES
        ('Drive My Car', 'https://m.media-amazon.com/images/I/81T3Qnqg4NL._AC_UY436_FMwebp_QL65_.jpg', 'August 20th, 2021', 'Drive My Car (Japanese: ドライブ・マイ・カー, Hepburn: Doraibu Mai Kā) is a 2021 Japanese drama film[4] directed by Ryusuke Hamaguchi and written by Hamaguchi and Takamasa Oe. It follows a theatre director (played by Hidetoshi Nishijima), who directs a multilingual production of Uncle Vanya while dealing with the death of his wife (Reika Kirishima).[5] It is based on Haruki Murakamis short story of the same name and other stories from his 2014 collection Men Without Women.[6] Tōko Miura, Park Yu-rim, Jin Dae-yeon, Sonia Yuan, Ahn Hwitae, Perry Dizon, Satoko Abe, and Masaki Okada also star.', '4');
